In [12]:
from typing import Tuple
import numpy as np
from tqdm import tqdm
from torch.utils.data import Dataset
import torch
import pandas as pd

max_time_delta = 0
mean_iri = 0
iri_range = 0

class IRIDataset(Dataset):
    def __init__(self, data: pd.DataFrame, seq_length=10, padding_value=-1):
        global max_time_delta

        self.__raw_data = data
        self.__padding_value = padding_value

        self._inputs = []
        self._outputs = []

        # This will split each sequence (SHRP_ID, STATE_CODE) into sequences of length seq_length
        # that contain between 1 and seq_length-1 rows from the original dataset
        main_bar = self.__raw_data.groupby(["SHRP_ID", "STATE_CODE"])
#         main_bar = tqdm(self.__raw_data.groupby(["SHRP_ID", "STATE_CODE"]), leave=False, desc="Generating sequences")
        for group in main_bar:
            data = group[1].sort_values(["VISIT_DATE"], ascending=True)
            data["RELATIVE_TIME"] = pd.to_datetime(data["VISIT_DATE"])

            # subtract the first date from all dates to get a relative date
            data["RELATIVE_TIME"] = data["RELATIVE_TIME"] - data["RELATIVE_TIME"].iloc[0]
            data["RELATIVE_TIME"] = data["RELATIVE_TIME"].dt.days
            local_max = data["RELATIVE_TIME"].max()
            if local_max > max_time_delta:
                max_time_delta = local_max

            for i in range(2, len(data)):
                print('i:',i)
                tmp = pd.DataFrame(data.iloc[:i])
                print('tmp:')
                print(tmp)
                # Pad the sequence to length seq_length
                pad = pd.DataFrame(self.__padding_value, index=range(seq_length - len(tmp)), columns=tmp.columns)
                print('pad:')
                print(pad)
                tmp = pd.concat([pad, tmp])[-seq_length:]
                print('final:')
                print(tmp)

                inputs = tmp[['IRI_LEFT_WHEEL_PATH', 'IRI_RIGHT_WHEEL_PATH', 'RELATIVE_TIME']].to_numpy(dtype=float)
                inputs[-1, 0] = -1
                inputs[-1, 1] = -1
                
                print('inputs:')
                print(inputs)

                self._inputs.append(inputs)
                self._outputs.append(data.iloc[i-1][['IRI_LEFT_WHEEL_PATH', 'IRI_RIGHT_WHEEL_PATH']].to_numpy(dtype=float))
            
            data.drop(columns=["VISIT_DATE"], inplace=True)

    def __len__(self):
        return len(self._inputs)
    
    def __getitem__(self, idx):
        normalized = self._inputs.copy()[idx]
        normalized[:, 2] = normalized[:, 2] # / max_time_delta
        return torch.from_numpy(normalized.T).float(), torch.from_numpy(self._outputs[idx]).float()

In [13]:
import pandas as pd
raw_data = pd.read_parquet(path="../training_data/final_data.parquet")
# IRIDataset1 = IRIDataset()
IRIDataset(raw_data)

i: 2
tmp:
                   VISIT_DATE  IRI_LEFT_WHEEL_PATH  IRI_RIGHT_WHEEL_PATH  \
SHRP_ID STATE_CODE                                                         
0001    48         1990-03-06               0.6904                0.6570   
        48         1992-03-17               0.6894                0.7312   

                    MAX_ANN_HUM_AVG  MIN_ANN_HUM_AVG  MEAN_ANN_TEMP_AVG  \
SHRP_ID STATE_CODE                                                        
0001    48                89.222222        44.814815          20.363636   
        48                89.222222        44.814815          20.363636   

                    FREEZE_THAW_YR  TOTAL_ANN_PRECIP  TOTAL_SNOWFALL_YR  \
SHRP_ID STATE_CODE                                                        
0001    48                15.30303        859.939394          12.424242   
        48                15.30303        859.939394          12.424242   

                    LAYER_TYPE  MAX_MEAN_DEPTH_WIRE_REF  AADT_ALL_VEHIC  \
SHRP_ID 

i: 6
tmp:
                   VISIT_DATE  IRI_LEFT_WHEEL_PATH  IRI_RIGHT_WHEEL_PATH  \
SHRP_ID STATE_CODE                                                         
0101    1          1995-10-30               0.6572                0.6574   
        1          1996-01-10               0.6962                0.6384   
        1          1996-04-08               0.6508                0.7148   
        1          1996-08-12               0.6804                0.7132   
        1          1996-10-11               0.6836                0.6724   
        1          1997-07-03               0.7046                0.6692   

                    MAX_ANN_HUM_AVG  MIN_ANN_HUM_AVG  MEAN_ANN_TEMP_AVG  \
SHRP_ID STATE_CODE                                                        
0101    1                 88.925926        44.185185          17.454545   
        1                 88.925926        44.185185          17.454545   
        1                 88.925926        44.185185          17.454545   
      

        10                                 -1.0            337  
pad:
   VISIT_DATE  IRI_LEFT_WHEEL_PATH  IRI_RIGHT_WHEEL_PATH  MAX_ANN_HUM_AVG  \
0          -1                   -1                    -1               -1   
1          -1                   -1                    -1               -1   
2          -1                   -1                    -1               -1   
3          -1                   -1                    -1               -1   
4          -1                   -1                    -1               -1   
5          -1                   -1                    -1               -1   

   MIN_ANN_HUM_AVG  MEAN_ANN_TEMP_AVG  FREEZE_THAW_YR  TOTAL_ANN_PRECIP  \
0               -1                 -1              -1                -1   
1               -1                 -1              -1                -1   
2               -1                 -1              -1                -1   
3               -1                 -1              -1                -1   
4              

6                           -1             -1  
final:
                     VISIT_DATE  IRI_LEFT_WHEEL_PATH  IRI_RIGHT_WHEEL_PATH  \
0                            -1              -1.0000               -1.0000   
1                            -1              -1.0000               -1.0000   
2                            -1              -1.0000               -1.0000   
3                            -1              -1.0000               -1.0000   
4                            -1              -1.0000               -1.0000   
5                            -1              -1.0000               -1.0000   
6                            -1              -1.0000               -1.0000   
(0101, 12)  1997-01-27 00:00:00               0.6858                0.9732   
(0101, 12)  2000-09-11 00:00:00               0.6606                0.8576   
(0101, 12)  2001-07-27 00:00:00               0.6932                0.8638   

            MAX_ANN_HUM_AVG  MIN_ANN_HUM_AVG  MEAN_ANN_TEMP_AVG  \
0                  

4                           -1             -1  
final:
                     VISIT_DATE  IRI_LEFT_WHEEL_PATH  IRI_RIGHT_WHEEL_PATH  \
0                            -1              -1.0000               -1.0000   
1                            -1              -1.0000               -1.0000   
2                            -1              -1.0000               -1.0000   
3                            -1              -1.0000               -1.0000   
4                            -1              -1.0000               -1.0000   
(0101, 19)  1993-10-15 00:00:00               1.0462                1.3368   
(0101, 19)  1995-02-15 00:00:00               1.2472                1.4340   
(0101, 19)  1996-04-16 00:00:00               1.4838                1.4882   
(0101, 19)  1997-09-25 00:00:00               1.5354                1.5696   
(0101, 19)  1998-10-13 00:00:00               1.5468                1.7562   

            MAX_ANN_HUM_AVG  MIN_ANN_HUM_AVG  MEAN_ANN_TEMP_AVG  \
0                 -

final:
                     VISIT_DATE  IRI_LEFT_WHEEL_PATH  IRI_RIGHT_WHEEL_PATH  \
0                            -1              -1.0000               -1.0000   
1                            -1              -1.0000               -1.0000   
2                            -1              -1.0000               -1.0000   
3                            -1              -1.0000               -1.0000   
(0101, 32)  1996-12-03 00:00:00               0.7536                0.9078   
(0101, 32)  1997-03-08 00:00:00               0.7400                0.8908   
(0101, 32)  1997-04-22 00:00:00               0.7438                0.8978   
(0101, 32)  1997-08-02 00:00:00               0.7446                0.9020   
(0101, 32)  1997-09-16 00:00:00               0.7502                0.8928   
(0101, 32)  1997-11-18 00:00:00               0.7456                0.9352   

            MAX_ANN_HUM_AVG  MIN_ANN_HUM_AVG  MEAN_ANN_TEMP_AVG  \
0                 -1.000000             -1.0          -1.000000   


final:
                     VISIT_DATE  IRI_LEFT_WHEEL_PATH  IRI_RIGHT_WHEEL_PATH  \
(0101, 32)  1997-11-18 00:00:00               0.7456                0.9352   
(0101, 32)  1998-08-28 00:00:00               0.7662                0.9136   
(0101, 32)  1999-10-16 00:00:00               0.7298                0.9044   
(0101, 32)  2000-02-03 00:00:00               0.7218                0.8952   
(0101, 32)  2000-04-20 00:00:00               0.7330                0.8972   
(0101, 32)  2000-06-14 00:00:00               0.7440                0.8824   
(0101, 32)  2000-09-11 00:00:00               0.7598                0.8794   
(0101, 32)  2000-11-17 00:00:00               0.7360                0.8782   
(0101, 32)  2001-02-26 00:00:00               0.7394                0.8788   
(0101, 32)  2001-04-18 00:00:00               0.7336                0.8844   

            MAX_ANN_HUM_AVG  MIN_ANN_HUM_AVG  MEAN_ANN_TEMP_AVG  \
(0101, 32)        73.592593             29.0          10.030303   


inputs:
[[ 7.45400000e-01  8.85000014e-01  1.65900000e+03]
 [ 7.27800000e-01  8.79600000e-01  1.78500000e+03]
 [ 7.33600008e-01  8.84399986e-01  1.83900000e+03]
 [ 7.30799997e-01  8.90799999e-01  1.86800000e+03]
 [ 7.31599986e-01  8.91599989e-01  1.95100000e+03]
 [ 7.25699997e-01  8.78699994e-01  2.01500000e+03]
 [ 7.09800005e-01  8.80200004e-01  2.06600000e+03]
 [ 6.99599993e-01  8.82400000e-01  2.19800000e+03]
 [ 6.88999999e-01  8.78400004e-01  2.23200000e+03]
 [-1.00000000e+00 -1.00000000e+00  2.29400000e+03]]
i: 26
tmp:
                   VISIT_DATE  IRI_LEFT_WHEEL_PATH  IRI_RIGHT_WHEEL_PATH  \
SHRP_ID STATE_CODE                                                         
0101    32         1996-12-03               0.7536                0.9078   
        32         1997-03-08               0.7400                0.8908   
        32         1997-04-22               0.7438                0.8978   
        32         1997-08-02               0.7446                0.9020   
        32    

        1                                  26.2           1147  
pad:
   VISIT_DATE  IRI_LEFT_WHEEL_PATH  IRI_RIGHT_WHEEL_PATH  MAX_ANN_HUM_AVG  \
0          -1                   -1                    -1               -1   
1          -1                   -1                    -1               -1   

   MIN_ANN_HUM_AVG  MEAN_ANN_TEMP_AVG  FREEZE_THAW_YR  TOTAL_ANN_PRECIP  \
0               -1                 -1              -1                -1   
1               -1                 -1              -1                -1   

   TOTAL_SNOWFALL_YR  LAYER_TYPE  MAX_MEAN_DEPTH_WIRE_REF  AADT_ALL_VEHIC  \
0                 -1          -1                       -1              -1   
1                 -1          -1                       -1              -1   

   MEPDG_TRANS_CRACK_LENGTH_AC  RELATIVE_TIME  
0                           -1             -1  
1                           -1             -1  
final:
                    VISIT_DATE  IRI_LEFT_WHEEL_PATH  IRI_RIGHT_WHEEL_PATH  \
0           

(0102, 10)                         -1.0            697  
inputs:
[[ -1.          -1.          -1.        ]
 [ -1.          -1.          -1.        ]
 [ -1.          -1.          -1.        ]
 [ -1.          -1.          -1.        ]
 [ -1.          -1.          -1.        ]
 [ -1.          -1.          -1.        ]
 [  0.79579999   1.00740001   0.        ]
 [  0.7182       0.78100002 472.        ]
 [  0.797        0.90300001 583.        ]
 [ -1.          -1.         697.        ]]
i: 5
tmp:
                   VISIT_DATE  IRI_LEFT_WHEEL_PATH  IRI_RIGHT_WHEEL_PATH  \
SHRP_ID STATE_CODE                                                         
0102    10         1996-02-24               0.7958                1.0074   
        10         1997-06-10               0.7182                0.7810   
        10         1997-09-29               0.7970                0.9030   
        10         1998-01-21               0.7530                0.8806   
        10         1998-02-25               0.77

i: 2
tmp:
                   VISIT_DATE  IRI_LEFT_WHEEL_PATH  IRI_RIGHT_WHEEL_PATH  \
SHRP_ID STATE_CODE                                                         
0102    12         1997-01-27               0.6578                0.8678   
        12         1997-09-15               0.6486                0.8686   

                    MAX_ANN_HUM_AVG  MIN_ANN_HUM_AVG  MEAN_ANN_TEMP_AVG  \
SHRP_ID STATE_CODE                                                        
0102    12                 90.37037        56.148148          23.069767   
        12                 90.37037        56.148148          23.069767   

                    FREEZE_THAW_YR  TOTAL_ANN_PRECIP  TOTAL_SNOWFALL_YR  \
SHRP_ID STATE_CODE                                                        
0102    12                1.069767       1365.069767                0.0   
        12                1.069767       1365.069767                0.0   

                    LAYER_TYPE  MAX_MEAN_DEPTH_WIRE_REF  AADT_ALL_VEHIC  \
SHRP_ID 

        12                                34.34           4758  
pad:
Empty DataFrame
Columns: [VISIT_DATE, IRI_LEFT_WHEEL_PATH, IRI_RIGHT_WHEEL_PATH, MAX_ANN_HUM_AVG, MIN_ANN_HUM_AVG, MEAN_ANN_TEMP_AVG, FREEZE_THAW_YR, TOTAL_ANN_PRECIP, TOTAL_SNOWFALL_YR, LAYER_TYPE, MAX_MEAN_DEPTH_WIRE_REF, AADT_ALL_VEHIC, MEPDG_TRANS_CRACK_LENGTH_AC, RELATIVE_TIME]
Index: []
final:
                     VISIT_DATE  IRI_LEFT_WHEEL_PATH  IRI_RIGHT_WHEEL_PATH  \
(0102, 12)  2000-09-11 00:00:00               0.6684                0.8608   
(0102, 12)  2001-07-27 00:00:00               0.6658                0.8548   
(0102, 12)  2002-10-28 00:00:00               0.6864                0.8690   
(0102, 12)  2003-07-25 00:00:00               0.8484                0.7950   
(0102, 12)  2004-04-05 00:00:00               0.6966                0.9756   
(0102, 12)  2005-04-26 00:00:00               0.7730                0.8728   
(0102, 12)  2006-07-26 00:00:00               0.7628                0.9290   
(0102

7                           -1             -1  
final:
                     VISIT_DATE  IRI_LEFT_WHEEL_PATH  IRI_RIGHT_WHEEL_PATH  \
0                            -1              -1.0000               -1.0000   
1                            -1              -1.0000               -1.0000   
2                            -1              -1.0000               -1.0000   
3                            -1              -1.0000               -1.0000   
4                            -1              -1.0000               -1.0000   
5                            -1              -1.0000               -1.0000   
6                            -1              -1.0000               -1.0000   
7                            -1              -1.0000               -1.0000   
(0102, 32)  1997-04-22 00:00:00               0.6552                0.7526   
(0102, 32)  1997-11-18 00:00:00               0.6062                0.7084   

            MAX_ANN_HUM_AVG  MIN_ANN_HUM_AVG  MEAN_ANN_TEMP_AVG  \
0                 -

(0103, 1)                    19.033333           1890  
inputs:
[[-1.00000000e+00 -1.00000000e+00 -1.00000000e+00]
 [-1.00000000e+00 -1.00000000e+00 -1.00000000e+00]
 [-1.00000000e+00 -1.00000000e+00 -1.00000000e+00]
 [-1.00000000e+00 -1.00000000e+00 -1.00000000e+00]
 [-1.00000000e+00 -1.00000000e+00 -1.00000000e+00]
 [ 8.08800018e-01  7.78400004e-01  0.00000000e+00]
 [ 7.93800008e-01  7.25000000e-01  5.40000000e+02]
 [ 7.95199990e-01  8.00799990e-01  7.48000000e+02]
 [ 8.41999996e-01  8.20400000e-01  1.35700000e+03]
 [-1.00000000e+00 -1.00000000e+00  1.89000000e+03]]
i: 6
tmp:
                   VISIT_DATE  IRI_LEFT_WHEEL_PATH  IRI_RIGHT_WHEEL_PATH  \
SHRP_ID STATE_CODE                                                         
0103    1          1996-01-10               0.8088                0.7784   
        1          1997-07-03               0.7938                0.7250   
        1          1998-01-27               0.7952                0.8008   
        1          1999-09-28      

        10                                 -1.0           2006  
pad:
Empty DataFrame
Columns: [VISIT_DATE, IRI_LEFT_WHEEL_PATH, IRI_RIGHT_WHEEL_PATH, MAX_ANN_HUM_AVG, MIN_ANN_HUM_AVG, MEAN_ANN_TEMP_AVG, FREEZE_THAW_YR, TOTAL_ANN_PRECIP, TOTAL_SNOWFALL_YR, LAYER_TYPE, MAX_MEAN_DEPTH_WIRE_REF, AADT_ALL_VEHIC, MEPDG_TRANS_CRACK_LENGTH_AC, RELATIVE_TIME]
Index: []
final:
                     VISIT_DATE  IRI_LEFT_WHEEL_PATH  IRI_RIGHT_WHEEL_PATH  \
(0103, 10)  1997-06-10 00:00:00               0.7608                0.7358   
(0103, 10)  1997-09-29 00:00:00               0.7554                0.6896   
(0103, 10)  1998-02-25 00:00:00               0.7394                0.7330   
(0103, 10)  1998-05-13 00:00:00               0.7430                0.7134   
(0103, 10)  1998-07-28 00:00:00               0.7758                0.7176   
(0103, 10)  1998-11-05 00:00:00               0.7678                0.7370   
(0103, 10)  2000-12-06 00:00:00               0.8102                0.7046   
(0103

        12                                 9.37           4484  
pad:
Empty DataFrame
Columns: [VISIT_DATE, IRI_LEFT_WHEEL_PATH, IRI_RIGHT_WHEEL_PATH, MAX_ANN_HUM_AVG, MIN_ANN_HUM_AVG, MEAN_ANN_TEMP_AVG, FREEZE_THAW_YR, TOTAL_ANN_PRECIP, TOTAL_SNOWFALL_YR, LAYER_TYPE, MAX_MEAN_DEPTH_WIRE_REF, AADT_ALL_VEHIC, MEPDG_TRANS_CRACK_LENGTH_AC, RELATIVE_TIME]
Index: []
final:
                     VISIT_DATE  IRI_LEFT_WHEEL_PATH  IRI_RIGHT_WHEEL_PATH  \
(0103, 12)  1997-01-27 00:00:00               0.6008                0.8690   
(0103, 12)  2000-09-11 00:00:00               0.6372                0.8506   
(0103, 12)  2001-07-27 00:00:00               0.6298                0.8490   
(0103, 12)  2002-10-28 00:00:00               0.6458                0.8012   
(0103, 12)  2003-07-25 00:00:00               0.7854                0.8040   
(0103, 12)  2004-04-05 00:00:00               0.7358                0.9746   
(0103, 12)  2005-04-26 00:00:00               0.7662                0.9652   
(0103

        20                              31.2875            281  
pad:
   VISIT_DATE  IRI_LEFT_WHEEL_PATH  IRI_RIGHT_WHEEL_PATH  MAX_ANN_HUM_AVG  \
0          -1                   -1                    -1               -1   
1          -1                   -1                    -1               -1   
2          -1                   -1                    -1               -1   
3          -1                   -1                    -1               -1   
4          -1                   -1                    -1               -1   
5          -1                   -1                    -1               -1   
6          -1                   -1                    -1               -1   
7          -1                   -1                    -1               -1   

   MIN_ANN_HUM_AVG  MEAN_ANN_TEMP_AVG  FREEZE_THAW_YR  TOTAL_ANN_PRECIP  \
0               -1                 -1              -1                -1   
1               -1                 -1              -1                -1   
2          

i: 7
tmp:
                   VISIT_DATE  IRI_LEFT_WHEEL_PATH  IRI_RIGHT_WHEEL_PATH  \
SHRP_ID STATE_CODE                                                         
0103    32         1997-04-22               0.6880                0.7694   
        32         1997-11-18               0.6924                0.7576   
        32         1998-08-28               0.7060                0.7682   
        32         1999-10-16               0.7458                0.7624   
        32         2000-06-14               0.7228                0.7322   
        32         2001-06-19               0.7210                0.7398   
        32         2002-06-10               0.7210                0.7242   

                    MAX_ANN_HUM_AVG  MIN_ANN_HUM_AVG  MEAN_ANN_TEMP_AVG  \
SHRP_ID STATE_CODE                                                        
0103    32                73.592593             29.0          10.030303   
        32                73.592593             29.0          10.030303   
     

3                           -1             -1  
final:
                    VISIT_DATE  IRI_LEFT_WHEEL_PATH  IRI_RIGHT_WHEEL_PATH  \
0                           -1              -1.0000               -1.0000   
1                           -1              -1.0000               -1.0000   
2                           -1              -1.0000               -1.0000   
3                           -1              -1.0000               -1.0000   
(0104, 1)  1996-01-10 00:00:00               0.6380                0.5504   
(0104, 1)  1997-07-03 00:00:00               0.7078                0.5778   
(0104, 1)  1998-01-27 00:00:00               0.6762                0.6032   
(0104, 1)  1998-04-23 00:00:00               0.7110                0.6298   
(0104, 1)  1999-09-28 00:00:00               0.6648                0.5980   
(0104, 1)  2001-03-14 00:00:00               0.7026                0.5928   

           MAX_ANN_HUM_AVG  MIN_ANN_HUM_AVG  MEAN_ANN_TEMP_AVG  \
0                -1.000000     

        10                                 -1.0           2006  
pad:
Empty DataFrame
Columns: [VISIT_DATE, IRI_LEFT_WHEEL_PATH, IRI_RIGHT_WHEEL_PATH, MAX_ANN_HUM_AVG, MIN_ANN_HUM_AVG, MEAN_ANN_TEMP_AVG, FREEZE_THAW_YR, TOTAL_ANN_PRECIP, TOTAL_SNOWFALL_YR, LAYER_TYPE, MAX_MEAN_DEPTH_WIRE_REF, AADT_ALL_VEHIC, MEPDG_TRANS_CRACK_LENGTH_AC, RELATIVE_TIME]
Index: []
final:
                     VISIT_DATE  IRI_LEFT_WHEEL_PATH  IRI_RIGHT_WHEEL_PATH  \
(0104, 10)  1997-06-10 00:00:00               0.8034                0.8640   
(0104, 10)  1997-09-29 00:00:00               0.7850                0.8548   
(0104, 10)  1998-02-25 00:00:00               0.7600                0.8304   
(0104, 10)  1998-05-13 00:00:00               0.7776                0.8356   
(0104, 10)  1998-07-28 00:00:00               0.8068                0.8530   
(0104, 10)  1998-11-05 00:00:00               0.7698                0.8458   
(0104, 10)  2000-12-06 00:00:00               0.7658                0.8192   
(0104

(0104, 12)                        15.21           3011  
inputs:
[[ 6.18200004e-01  7.79799998e-01  0.00000000e+00]
 [ 5.77599990e-01  7.74599993e-01  2.31000000e+02]
 [ 6.03600001e-01  8.71200001e-01  3.74000000e+02]
 [ 6.40999997e-01  7.87600005e-01  6.83000000e+02]
 [ 6.01000011e-01  7.73200011e-01  1.32300000e+03]
 [ 5.90800011e-01  7.66200006e-01  1.64200000e+03]
 [ 6.17200005e-01  7.99600005e-01  2.10000000e+03]
 [ 7.62400007e-01  7.69400012e-01  2.37000000e+03]
 [ 6.76999998e-01  8.35799992e-01  2.62500000e+03]
 [-1.00000000e+00 -1.00000000e+00  3.01100000e+03]]
i: 11
tmp:
                   VISIT_DATE  IRI_LEFT_WHEEL_PATH  IRI_RIGHT_WHEEL_PATH  \
SHRP_ID STATE_CODE                                                         
0104    12         1997-01-27               0.6182                0.7798   
        12         1997-09-15               0.5776                0.7746   
        12         1998-02-05               0.6036                0.8712   
        12         1998-12-11    

        19                           189.833333           2852  
pad:
   VISIT_DATE  IRI_LEFT_WHEEL_PATH  IRI_RIGHT_WHEEL_PATH  MAX_ANN_HUM_AVG  \
0          -1                   -1                    -1               -1   

   MIN_ANN_HUM_AVG  MEAN_ANN_TEMP_AVG  FREEZE_THAW_YR  TOTAL_ANN_PRECIP  \
0               -1                 -1              -1                -1   

   TOTAL_SNOWFALL_YR  LAYER_TYPE  MAX_MEAN_DEPTH_WIRE_REF  AADT_ALL_VEHIC  \
0                 -1          -1                       -1              -1   

   MEPDG_TRANS_CRACK_LENGTH_AC  RELATIVE_TIME  
0                           -1             -1  
final:
                     VISIT_DATE  IRI_LEFT_WHEEL_PATH  IRI_RIGHT_WHEEL_PATH  \
0                            -1              -1.0000               -1.0000   
(0104, 19)  1993-10-15 00:00:00               0.8418                0.7650   
(0104, 19)  1995-02-15 00:00:00               0.9518                0.8626   
(0104, 19)  1996-04-16 00:00:00               1.1820  

5                           -1             -1  
final:
                     VISIT_DATE  IRI_LEFT_WHEEL_PATH  IRI_RIGHT_WHEEL_PATH  \
0                            -1              -1.0000               -1.0000   
1                            -1              -1.0000               -1.0000   
2                            -1              -1.0000               -1.0000   
3                            -1              -1.0000               -1.0000   
4                            -1              -1.0000               -1.0000   
5                            -1              -1.0000               -1.0000   
(0104, 32)  1997-04-22 00:00:00               0.5930                0.7450   
(0104, 32)  1997-11-18 00:00:00               0.5836                0.7442   
(0104, 32)  1998-08-28 00:00:00               0.5864                0.7606   
(0104, 32)  1999-10-16 00:00:00               0.5896                0.7356   

            MAX_ANN_HUM_AVG  MIN_ANN_HUM_AVG  MEAN_ANN_TEMP_AVG  \
0                 -

i: 6
tmp:
                   VISIT_DATE  IRI_LEFT_WHEEL_PATH  IRI_RIGHT_WHEEL_PATH  \
SHRP_ID STATE_CODE                                                         
0104    39         1996-08-14               0.7544                0.7274   
        39         1996-12-27               0.8584                0.8110   
        39         1997-12-08               1.0222                0.9940   
        39         1998-11-12               1.2584                1.1542   
        39         1999-10-20               1.3230                1.2550   
        39         2000-08-16               1.3504                1.2736   

                    MAX_ANN_HUM_AVG  MIN_ANN_HUM_AVG  MEAN_ANN_TEMP_AVG  \
SHRP_ID STATE_CODE                                                        
0104    39                    85.75            47.75           10.44898   
        39                    85.75            47.75           10.44898   
        39                    85.75            47.75           10.44898   
      

(0104, 39)                     2.791667           5417  
inputs:
[[ 1.41500001e+00  1.42880001e+00  1.90800000e+03]
 [ 1.41459999e+00  1.32320001e+00  2.30500000e+03]
 [ 1.42719998e+00  1.35080001e+00  2.44900000e+03]
 [ 1.56860001e+00  1.46999998e+00  2.73000000e+03]
 [ 1.48060000e+00  1.43559999e+00  3.18600000e+03]
 [ 1.47139997e+00  1.49840002e+00  3.64700000e+03]
 [ 1.53999999e+00  1.54679997e+00  4.35200000e+03]
 [ 1.67119999e+00  1.58099999e+00  4.81500000e+03]
 [ 1.70000000e+00  1.69899998e+00  5.11000000e+03]
 [-1.00000000e+00 -1.00000000e+00  5.41700000e+03]]
i: 17
tmp:
                   VISIT_DATE  IRI_LEFT_WHEEL_PATH  IRI_RIGHT_WHEEL_PATH  \
SHRP_ID STATE_CODE                                                         
0104    39         1996-08-14               0.7544                0.7274   
        39         1996-12-27               0.8584                0.8110   
        39         1997-12-08               1.0222                0.9940   
        39         1998-11-12    

i: 2
tmp:
                   VISIT_DATE  IRI_LEFT_WHEEL_PATH  IRI_RIGHT_WHEEL_PATH  \
SHRP_ID STATE_CODE                                                         
0105    10         1997-06-10               0.6538                0.7356   
        10         1997-09-29               0.6190                0.7126   

                    MAX_ANN_HUM_AVG  MIN_ANN_HUM_AVG  MEAN_ANN_TEMP_AVG  \
SHRP_ID STATE_CODE                                                        
0105    10                     93.9             50.2          13.340426   
        10                     93.9             50.2          13.340426   

                    FREEZE_THAW_YR  TOTAL_ANN_PRECIP  TOTAL_SNOWFALL_YR  \
SHRP_ID STATE_CODE                                                        
0105    10                77.12766       1145.638298         355.340426   
        10                77.12766       1145.638298         355.340426   

                    LAYER_TYPE  MAX_MEAN_DEPTH_WIRE_REF  AADT_ALL_VEHIC  \
SHRP_ID 

i: 13
tmp:
                   VISIT_DATE  IRI_LEFT_WHEEL_PATH  IRI_RIGHT_WHEEL_PATH  \
SHRP_ID STATE_CODE                                                         
0105    10         1997-06-10               0.6538                0.7356   
        10         1997-09-29               0.6190                0.7126   
        10         1998-02-25               0.6238                0.7126   
        10         1998-05-13               0.6516                0.7266   
        10         1998-07-28               0.6456                0.7414   
        10         1998-11-05               0.6526                0.7402   
        10         2000-12-06               0.6454                0.8230   
        10         2001-07-12               0.6412                0.8560   
        10         2002-04-26               0.6572                0.8814   
        10         2002-12-07               0.6580                0.8484   
        10         2003-08-21               0.6894                0.9358   
 

(0105, 19)                   130.983333            488  
inputs:
[[ -1.          -1.          -1.        ]
 [ -1.          -1.          -1.        ]
 [ -1.          -1.          -1.        ]
 [ -1.          -1.          -1.        ]
 [ -1.          -1.          -1.        ]
 [ -1.          -1.          -1.        ]
 [ -1.          -1.          -1.        ]
 [ -1.          -1.          -1.        ]
 [  1.00980002   1.05420001   0.        ]
 [ -1.          -1.         488.        ]]
i: 3
tmp:
                   VISIT_DATE  IRI_LEFT_WHEEL_PATH  IRI_RIGHT_WHEEL_PATH  \
SHRP_ID STATE_CODE                                                         
0105    19         1993-10-15               1.0098                1.0542   
        19         1995-02-15               1.1630                1.1050   
        19         1996-04-16               1.4330                1.2376   

                    MAX_ANN_HUM_AVG  MIN_ANN_HUM_AVG  MEAN_ANN_TEMP_AVG  \
SHRP_ID STATE_CODE                              

4                           -1             -1  
final:
                     VISIT_DATE  IRI_LEFT_WHEEL_PATH  IRI_RIGHT_WHEEL_PATH  \
0                            -1              -1.0000               -1.0000   
1                            -1              -1.0000               -1.0000   
2                            -1              -1.0000               -1.0000   
3                            -1              -1.0000               -1.0000   
4                            -1              -1.0000               -1.0000   
(0105, 20)  1994-05-13 00:00:00               0.8090                0.9848   
(0105, 20)  1995-02-18 00:00:00               1.0322                1.1214   
(0105, 20)  1996-04-23 00:00:00               1.1988                1.3622   
(0105, 20)  1997-02-13 00:00:00               1.4692                1.4616   
(0105, 20)  1998-08-21 00:00:00               1.9446                2.1830   

            MAX_ANN_HUM_AVG  MIN_ANN_HUM_AVG  MEAN_ANN_TEMP_AVG  \
0                  

(0105, 39)                         -1.0            135  
inputs:
[[ -1.          -1.          -1.        ]
 [ -1.          -1.          -1.        ]
 [ -1.          -1.          -1.        ]
 [ -1.          -1.          -1.        ]
 [ -1.          -1.          -1.        ]
 [ -1.          -1.          -1.        ]
 [ -1.          -1.          -1.        ]
 [ -1.          -1.          -1.        ]
 [  1.06399999   1.11199997   0.        ]
 [ -1.          -1.         135.        ]]
i: 2
tmp:
                   VISIT_DATE  IRI_LEFT_WHEEL_PATH  IRI_RIGHT_WHEEL_PATH  \
SHRP_ID STATE_CODE                                                         
0106    1          1994-08-25               0.5538                0.9402   
        1          1996-01-10               0.6028                0.5608   

                    MAX_ANN_HUM_AVG  MIN_ANN_HUM_AVG  MEAN_ANN_TEMP_AVG  \
SHRP_ID STATE_CODE                                                        
0106    1                 88.925926        44.185

(0106, 10)                         -1.0            337  
inputs:
[[ -1.          -1.          -1.        ]
 [ -1.          -1.          -1.        ]
 [ -1.          -1.          -1.        ]
 [ -1.          -1.          -1.        ]
 [ -1.          -1.          -1.        ]
 [ -1.          -1.          -1.        ]
 [  0.81639999   0.67639999   0.        ]
 [  0.7232       0.65       111.        ]
 [  0.76960001   0.6446     260.        ]
 [ -1.          -1.         337.        ]]
i: 5
tmp:
                   VISIT_DATE  IRI_LEFT_WHEEL_PATH  IRI_RIGHT_WHEEL_PATH  \
SHRP_ID STATE_CODE                                                         
0106    10         1997-06-10               0.8164                0.6764   
        10         1997-09-29               0.7232                0.6500   
        10         1998-02-25               0.7696                0.6446   
        10         1998-05-13               0.7658                0.6528   
        10         1998-07-28               0.73

KeyboardInterrupt: 

In [11]:
raw_data = pd.read_parquet(path="../training_data/final_data.parquet")
raw_data

VISIT_DATE  IRI_LEFT_WHEEL_PATH  IRI_RIGHT_WHEEL_PATH  \
SHRP_ID STATE_CODE                                                         
0001    48         1990-03-06               0.6904                0.6570   
        48         1992-03-17               0.6894                0.7312   
        48         1993-07-13               0.7472                0.6938   
        48         1995-05-03               0.7092                0.7838   
        48         1997-08-06               0.7600                0.7508   
...                       ...                  ...                   ...   
Q350    48         1995-05-01               1.2042                1.1674   
        48         2001-04-18               1.1592                1.0578   
Q353    48         1990-09-17               1.1030                0.7784   
        48         1995-05-01               1.2294                1.0444   
        48         2001-04-18               1.1338                0.9110   

                    MAX_ANN_HUM_AVG  MIN_ANN_HUM_AVG  MEAN_ANN_TEMP_AVG  \
SHRP_ID STATE_CODE                                                        
0001    48                89.222222        44.814815          20.363636   
        48                89.222222        44.814815          20.363636   
        48                89.222222        44.814815          20.363636   
        48                89.222222        44.814815          20.363636   
        48                89.222222        44.814815          20.363636   
...                             ...              ...                ...   
Q350    48                88.333333        43.666667          18.636364   
        48                88.333333        43.666667          18.636364   
Q353    48                88.333333        43.666667          18.636364   
        48                88.333333        43.666667          18.636364   
        48                88.333333        43.666667          18.636364   

                    FREEZE_THAW_YR  TOTAL_ANN_PRECIP  TOTAL_SNOWFALL_YR  \
SHRP_ID STATE_CODE                                                        
0001    48               15.303030        859.939394          12.424242   
        48               15.303030        859.939394          12.424242   
        48               15.303030        859.939394          12.424242   
        48               15.303030        859.939394          12.424242   
        48               15.303030        859.939394          12.424242   
...                            ...               ...                ...   
Q350    48               36.295455        743.522727          15.431818   
        48               36.295455        743.522727          15.431818   
Q353    48               36.295455        743.522727          15.431818   
        48               36.295455        743.522727          15.431818   
        48               36.295455        743.522727          15.431818   

                    LAYER_TYPE  MAX_MEAN_DEPTH_WIRE_REF  AADT_ALL_VEHIC  \
SHRP_ID STATE_CODE                                                        
0001    48                   0                 5.142857       -1.000000   
        48                   0                 5.142857       -1.000000   
        48                   0                 5.142857       -1.000000   
        48                   0                 5.142857       -1.000000   
        48                   0                 5.142857       -1.000000   
...                        ...                      ...             ...   
Q350    48                   0                10.000000     1158.809524   
        48                   0                10.000000     1158.809524   
Q353    48                   0                 8.500000     1158.809524   
        48                   0                 8.500000     1158.809524   
        48                   0                 8.500000     1158.809524   

                    MEPDG_TRANS_CRACK_LENGTH_AC  
SHRP_ID STATE_CODE                               
00